### ISSUE TITLE
Is this still active

### ISSUE THREAD

**Issue by sjkeerthi** [coinkite/cloudfire#1]
Hi,

I am looking for the alternative to cloudflare to protect our customer websites and SaaS app. Is this project is still active.

**Comment by Mecanik** [comment]
Same question here... is this dead ?

**Comment by stemount** [comment]
I hope so, this looks very promising! I wonder if it works…

**Comment by mrchirub** [comment]
The demo website seems to be down, so I'd assume it's dead.

**Comment by modernn** [comment]
he's dead jim

**Comment by peter-conalgo** [comment]
yep dead
